name: Run Tests

on: [push, pull_request] 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Installer les dépendances
        run: npm install
        
      - name: Vérifier la version de Node.js
        run: node -v

      - name: Exécuter les tests unitaires
        run: npm test

     - name: Debug en cas d'erreur
        if: failure()
        run: cat test-results.xml